version: 2

jobs:
  build:
    machine: { image: "ubuntu-2004:202101-01" } # https://circleci.com/docs/2.0/arm-resources/
    resource_class: arm.medium # https://circleci.com/docs/2.0/arm-resources/#pricing-and-availability
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm i -g @dr-js/core@^0.4.20-dev.0

            echo "system: $(node -p "os.platform() + ' - ' + os.release() + ' [' + os.arch() + ']'")"
            echo "user: $(id)"
            echo "node: $(node -v)"
            echo "npm: $(npm -v)"

            echo '{ "experimental": true, "features": { "buildkit": true } }' | sudo tee /etc/docker/daemon.json
            sudo systemctl restart docker

            echo '"drjs/debian"' > source/debian10/BUILD_REPO.json
            echo '"ghcr.io/dr-js/debian"' > source/debian10/BUILD_REPO_GHCR.json

            echo '"drjs/debian"' > source/debian11/BUILD_REPO.json
            echo '"ghcr.io/dr-js/debian"' > source/debian11/BUILD_REPO_GHCR.json

            echo "${CIRCLECI_DOCKER_HUB_DRJS_PW}" | dr-js --docker -- login --username drjs --password-stdin
            echo "${CIRCLECI_GHCR_DRJS_PAT}" | dr-js --docker -- login --username dr-js --password-stdin ghcr.io
      - run: npm ci
      - run: npm test
      - run: npm run build-debian11
      - run: npm run build-debian11-cn
      - run: npm run push-debian11-all

workflows:
  version: 2
  ci-tag-build:
    jobs:
      - build: # https://circleci.com/docs/2.0/configuration-reference/#tags
          filters:
            branches: { only: "no-branch" } # skip branch build
            tags: { only: "/v.*/" } # use `v0.0.0` tag pattern
