# extra command to append

SHELL [ "/bin/bash", "-c" ]

RUN set -ex
RUN apt-get update -yq

RUN apt-get install -yq --no-install-recommends \
  ca-certificates

RUN apt-get autoremove -yq --purge \
  -o APT::AutoRemove::RecommendsImportant=false

RUN shopt -s nullglob \
  && find /var/cache/apt/archives /var/lib/apt/lists /var/log /var/lib/dpkg/*-old /var/cache/debconf/*-old -not -name lock -type f -delete \
  && shopt -u nullglob
