name: ci-test

on:
  push: { branches: [ '**' ] }

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: ghcr.io/dr-js/debian:11-bin-git-0.2.9
    steps:
      - { uses: "actions/checkout@v2" } # https://github.com/actions/checkout
      - run: npx @dr-js/dev@0.4 -eI .github/ci-patch.js
      - run: npm ci
      - run: npm test
