name: ci-test

on:
  push: { branches: [ '**' ] }

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/dr-js/debian:10-bin-git-0.1.3
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Log CI info
        run: |
          echo "system: $(node -p "os.platform() + ' - ' + os.release() + ' [' + os.arch() + ']'")"
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"

      - run: npm ci
      - run: npm test
