name: ci-tag-build

on: # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
  push:
    tags:
      - 'v*' # use `v0.0.0` tag pattern
      # - '!v*-dev.*' # for dev tag like `v0.0.0-dev.0`, upload manually if needed

jobs:
  build:
    strategy:
      fail-fast: false # allow all test to run to the end
      matrix:
        os: [ ubuntu-latest ] # [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 14.x ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Git repo
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Log CI info & Setup Docker # https://stackoverflow.com/questions/60171603/enable-experimental-features-on-github-workflow-images/60454218#60454218
        run: |
          echo "system: $(node -p "os.platform() + ' - ' + os.release() + ' [' + os.arch() + ']'")"
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"

          echo '{ "experimental": true, "features": { "buildkit": true } }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

          echo '"drjs/debian"' > source/debian10/BUILD_REPO.json
          echo '"ghcr.io/dr-js/debian"' > source/debian10/BUILD_REPO_GHCR.json

          echo "$PASSWORD" | docker login --username drjs --password-stdin
          echo "$GHCR_PASSWORD" | docker login --username dr-js --password-stdin ghcr.io
        env:
          PASSWORD: ${{ secrets.DOCKER_HUB_DRJS_PASSWORD }}
          GHCR_PASSWORD: ${{ secrets.GHCR_DRJS_PAT_PASSWORD }}

      - run: npm ci
      - run: npm run build-debian10
      - run: npm run build-debian10-cn
      - run: npm run docker-push-all
