name: ci-test

on:
  push: { branches: [ '**' ] }

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: ghcr.io/dr-js/debian:12-bin-git-0.3.4
    steps:
      - { uses: "actions/checkout@v3" } # https://github.com/actions/checkout
      # - run: npx @dr-js/dev@0.5 -eI .github/ci-patch.js # TODO: `npx` will use user 1001 & so later patch will error with: `sudo: you do not exist in the passwd database`
      - run: dr-js -eI .github/ci-patch.js # will run as root
      - run: npm ci
      - run: npm test
