name: "ci-tag-build"
on: { push: { tags: [ 'v*' ] } } # use `v0.0.0` tag pattern # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
jobs:
  build:
    timeout-minutes: 90
    runs-on: "ubuntu-latest"
    steps:
      - { uses: "actions/checkout@v4" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v4", with: { node-version: "20" } } # https://github.com/actions/setup-node
      - run: |
          bash .github/setup-docker.sh
          echo "$PASSWORD" | dr-js --docker -- login --username drjs --password-stdin
          echo "$GHCR_PASSWORD" | dr-js --docker -- login --username dr-js --password-stdin ghcr.io
        env:
          PASSWORD: ${{ secrets.DOCKER_HUB_DRJS_PASSWORD }}
          GHCR_PASSWORD: ${{ secrets.GHCR_DRJS_PAT_PASSWORD }}
      - run: npm ci
      - run: npm test
      - run: npm run build-debian12
      - run: npm run build-debian11
      - run: npm run push-debian12-all
      - run: npm run push-debian11-all
