name: ci-tag-build

on: # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
  push: { tags: [ 'v*' ] } # use `v0.0.0` tag pattern

jobs:
  build:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - { uses: "actions/checkout@v2" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v2", with: { node-version: "16.x" } } # https://github.com/actions/setup-node
      - run: npx @dr-js/dev@0.4 -eI .github/ci-patch.js
      - run: bash .github/setup-docker.sh
      - run: |
          echo "$PASSWORD" | dr-js --docker -- login --username drjs --password-stdin
          echo "$GHCR_PASSWORD" | dr-js --docker -- login --username dr-js --password-stdin ghcr.io
        env:
          PASSWORD: ${{ secrets.DOCKER_HUB_DRJS_PASSWORD }}
          GHCR_PASSWORD: ${{ secrets.GHCR_DRJS_PAT_PASSWORD }}
      - run: npm ci
      - run: npm test
      - run: npm run build-debian11
      # - run: npm run build-debian11-cn
      - run: npm run push-debian11-all
