name: ci-test

on:
  push: { branches: [ '**' ] }

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: ghcr.io/dr-js/debian:11-bin-git-0.2.4-dev.1
    steps:
      - { uses: "actions/checkout@v2" } # https://github.com/actions/checkout

      - name: Log CI info
        run: |
          echo "system: $(node -p "os.platform() + ' - ' + os.release() + ' [' + os.arch() + ']'")"
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"

      - run: npm ci
      - run: npm test
